using System.Net;
using System.Net.Http;
using System.Text;
using PlayFab;
using PlayFab.ServerModels;
using TankDraft.Server.PlayFab.Identity;

var checks = 0;
var now = new DateTimeOffset(2026, 9, 13, 12, 0, 0, TimeSpan.Zero);
await SuccessAsync(); await DenyVariantsAsync(); await CancellationAndCapacityAsync(); await HttpWireAndPolicyAsync(); await HttpCancellationAndCapacityAsync();
Console.WriteLine($"PASS PlayFab identity offline checks: {checks} cases; no credentials logged or PlayFab calls made.");

async Task SuccessAsync() { using var a = Adapter(_ => Task.FromResult(Result("ABCDE1"))); var v = await a.VerifyAsync("opaque+/=._-ticket", CancellationToken.None); Require(v?.AccountId == "ABCDE1" && v.ValidUntil == now.AddMinutes(2), "verified identity must contain only server account and <=2min expiry"); }
async Task DenyVariantsAsync()
{
    using var error = Adapter(_ => Task.FromResult(new PlayFabResult<AuthenticateSessionTicketResult> { Error = new PlayFabError() })); using var expired = Adapter(_ => Task.FromResult(new PlayFabResult<AuthenticateSessionTicketResult> { Result = new AuthenticateSessionTicketResult { IsSessionTicketExpired = true } })); using var malformed = Adapter(_ => Task.FromResult(Result("bad/id"))); using var nullUser = Adapter(_ => Task.FromResult(new PlayFabResult<AuthenticateSessionTicketResult> { Result = new AuthenticateSessionTicketResult() })); using var nullExpiry = Adapter(_ => Task.FromResult(new PlayFabResult<AuthenticateSessionTicketResult> { Result = new AuthenticateSessionTicketResult { UserInfo = new UserAccountInfo { PlayFabId = "ABCDE1" } } }));
    Require(await error.VerifyAsync(new string('a', 16), CancellationToken.None) is null, "SDK error denies"); Require(await expired.VerifyAsync(new string('a', 16), CancellationToken.None) is null, "expired denies"); Require(await malformed.VerifyAsync(new string('a', 16), CancellationToken.None) is null, "malformed PlayFab ID denies"); Require(await nullUser.VerifyAsync(new string('a', 16), CancellationToken.None) is null, "null UserInfo denies"); Require(await nullExpiry.VerifyAsync(new string('a', 16), CancellationToken.None) is null, "null expiry denies"); Require(await nullUser.VerifyAsync("bad", CancellationToken.None) is null, "malformed ticket denies before SDK"); Require(!new PlayFabIdentityOptions("B16D9", "injected-test-only").ToString().Contains("injected-test-only", StringComparison.Ordinal), "options ToString must redact secret");
}
async Task CancellationAndCapacityAsync()
{
    var started = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously); var finish = new TaskCompletionSource<PlayFabResult<AuthenticateSessionTicketResult>>(TaskCreationOptions.RunContinuationsAsynchronously); var calls = 0;
    using var a = new PlayFabIdentityAdapter(new PlayFabIdentityOptions("B16D9", "injected-test-only", 1), _ => { calls++; started.TrySetResult(); return finish.Task; }, () => now); using var pre = new CancellationTokenSource(); pre.Cancel(); await RequireCanceled(() => a.VerifyAsync(new string('a', 16), pre.Token), "pre-call cancellation"); Require(calls == 0, "pre-canceled call must not reach SDK"); using var during = new CancellationTokenSource(); var first = a.VerifyAsync(new string('a', 16), during.Token); await started.Task.WaitAsync(TimeSpan.FromSeconds(1)); during.Cancel(); await RequireBusy(() => a.VerifyAsync(new string('b', 16), CancellationToken.None), "inflight SDK call retains permit despite cancellation"); finish.SetResult(Result("ABCDE1")); await RequireCanceled(() => first, "cancellation after SDK completion denies identity"); var recovered = await a.VerifyAsync(new string('c', 16), CancellationToken.None); Require(recovered?.AccountId == "ABCDE1" && calls == 2, "completion releases capacity after the SDK task ends");
    var disposeStarted = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously); var disposeFinish = new TaskCompletionSource<PlayFabResult<AuthenticateSessionTicketResult>>(TaskCreationOptions.RunContinuationsAsynchronously); var disposable = new PlayFabIdentityAdapter(new PlayFabIdentityOptions("B16D9", "injected-test-only"), _ => { disposeStarted.TrySetResult(); return disposeFinish.Task; }, () => now); var pending = disposable.VerifyAsync(new string('d', 16), CancellationToken.None); await disposeStarted.Task.WaitAsync(TimeSpan.FromSeconds(1)); disposable.Dispose(); disposeFinish.SetResult(Result("ABCDE1")); Require((await pending)?.AccountId == "ABCDE1", "disposing during an injected task must not release a disposed semaphore");
}
async Task HttpWireAndPolicyAsync()
{
    var capture = new CapturingHandler((_, _) => Task.FromResult(Response(HttpStatusCode.OK, ValidJson("ABCDE1", false)))); using (var a = HttpAdapter(capture)) { var v = await a.VerifyAsync("opaque+/=._-ticket", CancellationToken.None); Require(v?.AccountId == "ABCDE1", "HTTP data must deserialize through SDK DTO"); }
    Require(capture.Method == HttpMethod.Post && capture.Uri == "https://b16d9.playfabapi.com/Server/AuthenticateSessionTicket", "HTTP endpoint must be pinned to validated TitleId"); Require(capture.Secret == "injected-test-only" && capture.Body == "{\"SessionTicket\":\"opaque+/=._-ticket\"}", "HTTP request must send only secret header and session ticket JSON"); Require(typeof(PlayFabIdentityHttpTransport).GetConstructors().All(c => !c.GetParameters().Any(p => p.ParameterType == typeof(HttpMessageHandler))), "production transport exposes no handler or TLS override"); RequireThrows(() => { using var ignored = new PlayFabIdentityHttpTransport(new PlayFabIdentityOptions("bad..", "injected-test-only")); }, "direct transport construction validates options");
    await RequireDenied(HttpStatusCode.Unauthorized, "invalid authentication HTTP response denies"); await RequireUnavailable(HttpStatusCode.TooManyRequests, "429 is unavailable"); await RequireUnavailable(HttpStatusCode.InternalServerError, "5xx is unavailable"); await RequireUnavailable(HttpStatusCode.Redirect, "redirect is unavailable"); await RequireUnavailableBody(new string('a', 256 * 1024 + 1), "oversized JSON is unavailable"); await RequireUnavailableBody("{\"code\":200,\"status\":\"OK\",\"data\":{\"UserInfo\":{\"PlayFabId\":\"ABCDE1\",\"PlayFabId\":\"ABCDE2\"},\"IsSessionTicketExpired\":false}}", "duplicate JSON properties are unavailable"); await RequireUnavailableBody("{\"code\":200,\"status\":\"OK\",\"data\":{\"UserInfo\":{\"PlayFabId\":\"ABCDE1\"},\"IsSessionTicketExpired\":false},\"Data\":{}}", "case-variant duplicate JSON properties are unavailable"); await RequireUnavailableBody("{\"status\":\"OK\",\"data\":{}}", "missing response code is unavailable"); await RequireUnavailableBody("{\"code\":201,\"status\":\"OK\",\"data\":{}}", "wrong response code is unavailable"); await RequireUnavailableBody("{\"code\":200,\"status\":\"OK\",\"error\":{},\"data\":{\"UserInfo\":{\"PlayFabId\":\"ABCDE1\"},\"IsSessionTicketExpired\":false}}", "error envelope with data is unavailable"); await RequireUnavailableBody("{\"code\":200,\"status\":\"OK\",\"data\":{\"UserInfo\":{\"PlayFabId\":\"ABCDE1\"},\"IsSessionTicketExpired\":\"false\"}}", "string expiry is unavailable"); await RequireUnavailableBody("{\"data\":", "truncated JSON is unavailable"); using var expired = HttpAdapter(new CapturingHandler((_, _) => Task.FromResult(Response(HttpStatusCode.OK, ValidJson("ABCDE1", true))))); Require(await expired.VerifyAsync(new string('a', 16), CancellationToken.None) is null, "expired HTTP response denies");
}
async Task HttpCancellationAndCapacityAsync()
{
    var calls = 0; var handler = new CapturingHandler(async (_, ct) => { if (Interlocked.Increment(ref calls) == 1) await Task.Delay(Timeout.InfiniteTimeSpan, ct); return Response(HttpStatusCode.OK, ValidJson("ABCDE1", false)); }); using var a = HttpAdapter(handler, 1); using var cancel = new CancellationTokenSource(); var hung = a.VerifyAsync(new string('a', 16), cancel.Token); await handler.Started.Task.WaitAsync(TimeSpan.FromSeconds(1)); await RequireBusy(() => a.VerifyAsync(new string('b', 16), CancellationToken.None), "hung HTTP work retains capacity"); cancel.Cancel(); await RequireCanceled(() => hung, "hung HTTP request honors cancellation"); var recovered = await a.VerifyAsync(new string('c', 16), CancellationToken.None); Require(recovered?.AccountId == "ABCDE1" && calls == 2, "canceled HTTP completion releases capacity");
    using var body = HttpAdapter(new CapturingHandler((_, _) => Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK) { Content = new BlockingContent() }))); using var bodyCancel = new CancellationTokenSource(); var pending = body.VerifyAsync(new string('a', 16), bodyCancel.Token); await Task.Yield(); bodyCancel.Cancel(); await RequireCanceled(() => pending, "body read honors cancellation");
}
async Task RequireDenied(HttpStatusCode status, string name) { using var a = HttpAdapter(new CapturingHandler((_, _) => Task.FromResult(Response(status, "{}")))); Require(await a.VerifyAsync(new string('a', 16), CancellationToken.None) is null, name); }
async Task RequireUnavailable(HttpStatusCode status, string name) { using var a = HttpAdapter(new CapturingHandler((_, _) => Task.FromResult(Response(status, "{}")))); await RequireUnavailableException(() => a.VerifyAsync(new string('a', 16), CancellationToken.None), name); }
async Task RequireUnavailableBody(string body, string name) { using var a = HttpAdapter(new CapturingHandler((_, _) => Task.FromResult(Response(HttpStatusCode.OK, body)))); await RequireUnavailableException(() => a.VerifyAsync(new string('a', 16), CancellationToken.None), name); }
PlayFabIdentityAdapter Adapter(Func<AuthenticateSessionTicketRequest, Task<PlayFabResult<AuthenticateSessionTicketResult>>> call) => new(new PlayFabIdentityOptions("B16D9", "injected-test-only"), call, () => now);
PlayFabIdentityAdapter HttpAdapter(HttpMessageHandler handler, int maximumInflight = 16) => new(new PlayFabIdentityOptions("B16D9", "injected-test-only", maximumInflight), handler, () => now);
PlayFabResult<AuthenticateSessionTicketResult> Result(string id) => new() { Result = new AuthenticateSessionTicketResult { IsSessionTicketExpired = false, UserInfo = new UserAccountInfo { PlayFabId = id } } };
HttpResponseMessage Response(HttpStatusCode status, string body) => new(status) { Content = new StringContent(body, Encoding.UTF8, "application/json") };
string ValidJson(string id, bool expired) => "{\"code\":200,\"status\":\"OK\",\"data\":{\"UserInfo\":{\"PlayFabId\":\"" + id + "\"},\"IsSessionTicketExpired\":" + expired.ToString().ToLowerInvariant() + "}}";
async Task RequireCanceled(Func<Task<VerifiedPlayFabIdentity?>> action, string name) { try { await action(); } catch (OperationCanceledException) { checks++; return; } throw new InvalidOperationException(name); }
async Task RequireBusy(Func<Task<VerifiedPlayFabIdentity?>> action, string name) { try { await action(); } catch (PlayFabIdentityBusyException) { checks++; return; } throw new InvalidOperationException(name); }
async Task RequireUnavailableException(Func<Task<VerifiedPlayFabIdentity?>> action, string name) { try { await action(); } catch (PlayFabIdentityUnavailableException e) { Require(e.Message == "Identity verification is temporarily unavailable.", "unavailable error is sanitized"); return; } throw new InvalidOperationException(name); }
void Require(bool value, string name) { if (!value) throw new InvalidOperationException(name); checks++; }
void RequireThrows(Action action, string name) { try { action(); } catch (ArgumentException) { checks++; return; } throw new InvalidOperationException(name); }
sealed class CapturingHandler(Func<HttpRequestMessage, CancellationToken, Task<HttpResponseMessage>> handler) : HttpMessageHandler { private readonly Func<HttpRequestMessage, CancellationToken, Task<HttpResponseMessage>> _handler = handler; public TaskCompletionSource Started { get; } = new(TaskCreationOptions.RunContinuationsAsynchronously); public HttpMethod? Method { get; private set; } public string? Uri { get; private set; } public string? Secret { get; private set; } public string? Body { get; private set; } protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken ct) { Method = request.Method; Uri = request.RequestUri?.AbsoluteUri; Secret = request.Headers.GetValues("X-SecretKey").Single(); Body = request.Content is null ? null : await request.Content.ReadAsStringAsync(ct); Started.TrySetResult(); return await _handler(request, ct); } }
sealed class BlockingContent : HttpContent { protected override bool TryComputeLength(out long length) { length = 0; return false; } protected override Task SerializeToStreamAsync(Stream stream, TransportContext? context) => throw new NotSupportedException(); protected override Task SerializeToStreamAsync(Stream stream, TransportContext? context, CancellationToken ct) => throw new NotSupportedException(); protected override Task<Stream> CreateContentReadStreamAsync() => Task.FromResult<Stream>(new BlockingStream()); protected override Task<Stream> CreateContentReadStreamAsync(CancellationToken ct) => Task.FromResult<Stream>(new BlockingStream()); }
sealed class BlockingStream : Stream { public override bool CanRead => true; public override bool CanSeek => false; public override bool CanWrite => false; public override long Length => throw new NotSupportedException(); public override long Position { get => 0; set => throw new NotSupportedException(); } public override void Flush() => throw new NotSupportedException(); public override int Read(byte[] buffer, int offset, int count) => throw new NotSupportedException(); public override ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken ct = default) => new(Task.Delay(Timeout.InfiniteTimeSpan, ct).ContinueWith(_ => { ct.ThrowIfCancellationRequested(); return 0; }, TaskScheduler.Default)); public override long Seek(long offset, SeekOrigin origin) => throw new NotSupportedException(); public override void SetLength(long value) => throw new NotSupportedException(); public override void Write(byte[] buffer, int offset, int count) => throw new NotSupportedException(); }
