<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TankDraft.Server.Admission/TankDraft.Server.Admission.csproj" />
    <ProjectReference Include="../TankDraft.Server.PlayFab.Identity/TankDraft.Server.PlayFab.Identity.csproj" />
  </ItemGroup>
</Project>
